modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
issueTrackerURL = "https://github.com/PaintNinja/Presence-Footsteps-Forge"

[[mods]]
modId = "presencefootsteps"
version = "1.19.2-1.6.4.1"
displayName = "Presence Footsteps (Forge)"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/presence-footsteps-forge"
updateJSONURL = "https://forge.curseupdate.com/433068/presencefootsteps"
authors = "Hurricaaane, Sollace, Paint_Ninja"
logoFile="presencefootsteps_logo.png"
description = "An overly complicated sound mod, ported to Forge."

[[dependencies.presencefootsteps]]
modId = "forge"
mandatory = true
versionRange = "[43.2.3,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.presencefootsteps]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2]"
ordering = "NONE"
side = "CLIENT"
