modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

[[mods]]
modId = "presencefootsteps"
version = "1.0.0"
displayName = "Presence Footsteps (Forge)"
authors = "Hurricaaane, Sollace, Paint_Ninja"
logoFile="presencefootsteps_logo.png"
description = '''
An overly complicated sound mod.
'''

[[dependencies.presencefootsteps]]
modId = "forge"
mandatory = true
versionRange = "[40.1.20,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.presencefootsteps]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "CLIENT"