modLoader = "javafml"
loaderVersion = "[49,)"
license = "MIT"
issueTrackerURL = "https://github.com/PaintNinja/Presence-Footsteps-Forge"
clientSideOnly = true

[[mods]]
modId = "presencefootsteps"
version = "1.20.4-1.12.0-beta.1"
displayName = "Presence Footsteps (Forge)"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/presence-footsteps-forge"
updateJSONURL = "https://forge.curseupdate.com/433068/presencefootsteps"
authors = "Hurricaaane, Sollace, Paint_Ninja"
logoFile="presencefootsteps_logo.png"
description = "An overly complicated sound mod, ported to Forge."

[[dependencies.presencefootsteps]]
modId = "forge"
mandatory = true
versionRange = "[49.0.38,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.presencefootsteps]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4]"
ordering = "NONE"
side = "CLIENT"
